apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: maven-demo
  name: maven-demo
  namespace: ai-app01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: maven-demo
    spec:
      containers:
        - env:
            - name: CACHE_IGNORE
              value: js|html
            - name: CACHE_PUBLIC_EXPIRATION
              value: 3d
          image: $REGISTRY/$HARBOR_NAMESPACE/$APP_NAME:$TAG_NAME
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          imagePullPolicy: Always
          name: maven-demo
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 100Mi
      imagePullSecrets:
      - name: harbor01
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: maven-demo-svc
  namespace: ai-app01
  labels:
    version: v1
    app: maven-demo
  annotations:
    kubesphere.io/serviceType: statelessservice
    prometheus.io/scrape: 'true'
spec:
  sessionAffinity: None
  selector:
    app: maven-demo
  ports:
  - name: http-0
    protocol: TCP
    port: 8080         #svc的端口
    targetPort: 8080   #pod内部的端口
  type: NodePort
  clusterIP:
  clusterIPs:
  internalTrafficPolicy: Cluster
  externalTrafficPolicy: Cluster
